apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prom-grafana-ing
  namespace: monitor-ns
spec:
  ingressClassName: nginx
  rules:
    - host: prom.eagunu4live.cloud
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: prometheus-server
                port:
                  number: 80
            path: /
    - host: manager.eagunu4live.cloud
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: prometheus-alertmanager
                port:
                  number: 80
            path: /
    - host: gra.eagunu4live.cloud
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
            path: /
    # - host: mongo-monitor.com
    #   http:
    #     paths:
    #       - pathType: Prefix
    #         backend:
    #           service:
    #             name: springappsvc
    #             port:
    #               number: 80
    #         path: /
